apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  MYSQL_HOST: catalog-db
  MYSQL_DB: catelog_db
  MYSQL_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
type: Opaque
stringData:
  MYSQL_PASSWORD: admin
